[package]
name = "spreadsheet-to-flow"
version = "0.1.0"
edition = "2021"
license = "MIT"
license-file = "LICENSE"

[dependencies]
serde_json = "1.0"
spreadsheet-ods = "0.25"
serde = { version = "1.0", features = ["derive"] }
